### ISSUE TITLE
En ny database version 13.4

### ISSUE THREAD

**Issue by RomanHVarinsky** [RomanHVarinsky/GC2-Vidi-Kerteminde#1]
Vi har et ønske om at få installeret en PostgreSQL-database v 13.4 ved siden af den eksisterende installation (v 11.7). Grunden til det er to QGIS-plugins (DAI-modul og SkadesØkonomi), der kræver en nyere version til at virke.

**Comment by RomanHVarinsky** [comment]
Kan den udveksle data med den eksisterende installation?

**Comment by mapcentia** [comment]
Ny PostGreSQL 13.7 er nu installeret. Jeg sender creds på mail

Det vil være muligt at bruge fremmed server til udveksling af data.

Men vil det ikke være en ide, at overføre clusteren fra den gamle version 11 og kun bruge 13, hvis der kan udveksles data?

**Comment by RomanHVarinsky** [comment]
Mener du at overføre hele databasen til version 13 og sløjfe 11? Det har jeg sådan set ikke et problem med, vi snakkede dog tidligere om at det pt ikke var nødvendigt at opgradere.
Ville det have betydning for nogle af de eksterne forbindelser, eller ville kunne 13'eren skifte til port 5432 efterfølgende?

**Comment by mapcentia** [comment]
Hvis de skal udveksle data, så tænker jeg, at det er det bedste, at kun have én. Altså sløjfe 11. Det vil ikke have betydning, da 13 vil efterfølgende blive bundet til port 5432

**Comment by RomanHVarinsky** [comment]
De skal nemlig kunne udveksle data, for jeg tænkte ikke at have de samme data liggende begge steder. 
Så jeg tænker godt du kan opgradere.

**Comment by RomanHVarinsky** [comment]
Har du evt en plan for hvornår du vil overføre clusteren til den nye version? Ingen pres, men det betyder vel at jeg ikke lægge nogen data i v13, eller? Ville clusteren overskrive dem, eller ville den lægge sig ved siden af (jeg tænker at skemaer får andre navne)?

**Comment by mapcentia** [comment]
Hvis du vil bruge data sammen, så skal alt ligge i samme database (kerteminde). Så hvis du opretter den på 13 vil den bliver overskrevet. Men vi kan blot dumpe dine schemaer inden og importerer dem ind igen efter flytningen. Men ellers tænker jeg, at vi gør det i næste uge. Jeg vil igangsætte en test, hvor vi lige tjekker, at flytningen fungerer, Derefter planlægger vi hvornår vi gør det. I må jo ikke opdatere noget efter flytningen er i gangsat

**Comment by RomanHVarinsky** [comment]
Det haster ikke mere så jeg sagtens kan vente til en gang i denne uge.

**Comment by RomanHVarinsky** [comment]
Hvad er status?

**Comment by mapcentia** [comment]
Jeg har nu lavet en test overførelse og du kan tjekke den. Du skal bare bruge port 5433.

Laget natur.kerteminde_draenkort kunne ikke overføres - det ser ud til at være et rasterkort?

Hvis alt ellers ser OK ud, så skal vi have aftalt et tidspunkt for den endelige overførelse.

**Comment by RomanHVarinsky** [comment]
Fint, jeg tjekker og melder tilbage. 
Ja, drænkortet er en raster - den kan jeg vist bare importere igen, eller?

**Comment by RomanHVarinsky** [comment]
Jeg kan umiddelbart ikke oprette forbindelsen til databasen - den melder timeout.

![image](https://user-images.githubusercontent.com/75674760/189848057-e53ac46b-4f64-48f6-99b5-b259b9b1e4ba.png)

**Comment by RomanHVarinsky** [comment]
Kunne det skyldes lukket port 5433?

**Comment by mapcentia** [comment]
Ja, den port er sikkert filtreret i firewall'en - jeg kan heller ikke udefra

**Comment by RomanHVarinsky** [comment]
Jeg skriver til IT

**Comment by RomanHVarinsky** [comment]
IT har åbnet for port 5433 og jeg er inde. Har du også brug for adgang? 
Er det noget særligt jeg skal tjekke efter?

**Comment by mapcentia** [comment]
Jeg behøver ikke at have adgang, da jeg kan gå gennem serveren.

Du skal blot lige tjekke, at du kan forbinde. Umiddelbart er drænkortet det eneste som fejlede

**Comment by RomanHVarinsky** [comment]
Jeg kan godt forbinde til den med 'gc2' brugeren, men ikke med 'rhv' brugeren... 

Unable to connect to server:

FATAL: no pg_hba.conf entry for host "192.168.143.95", user "rhv", database "kerteminde", SSL on
FATAL: no pg_hba.conf entry for host "192.168.143.95", user "rhv", database "kerteminde", SSL off

Men det skal jeg måske selv sørge for at rette.

**Comment by mapcentia** [comment]
Jeg har tilrette pg_hba.conf, så prøv nu igen

**Comment by RomanHVarinsky** [comment]
Jep, nu er det hul igennem for 'rhv'

**Comment by RomanHVarinsky** [comment]
Umiddelbart ser det ud til at virke, jeg kan læse data fra forskellige tabeller, views og fremmede tabeller.

**Comment by RomanHVarinsky** [comment]
Skal vi aftale et tidspunkt for migrering? Og når du nedlægger v11, bliver det gnidningsfrit overgang til v13 angående porten og adgang - her tænker jeg især på opkobling via QGIS hos mine kolleger?

**Comment by mapcentia** [comment]
Hvad siger du til fredag eftermiddag (30/9)?

**Comment by RomanHVarinsky** [comment]
Det er fint med mig - jeg når at skrive til folk at de ikke skal editere i databasen efter f.eks. kl 14. Har du brug for noget fra mig?

**Comment by mapcentia** [comment]
Nej, det skulle jeg ikke mene

**Comment by RomanHVarinsky** [comment]
Fint, vi har en aftale. Jeg skriver til kolleger om opgraderingen.

**Comment by mapcentia** [comment]
Database er flyttet til 13

**Comment by RomanHVarinsky** [comment]
Perfekt, tak. Jeg har ikke længere adgang til databasen på port 5433, så det må betyde at der nu kun findes én database i version 13 og du har fjernet version 11. Kan du bekræfte det? Så giver jeg nemlig melding til IT t de igen kan lukke for port 5433.

**Comment by mapcentia** [comment]
Det er korrekt

**Comment by RomanHVarinsky** [comment]
Fint, jeg lukker denne sag
