### ISSUE TITLE
Indlejrede kort på hjemmesiden fejler

### ISSUE THREAD

**Issue by RomanHVarinsky** [RomanHVarinsky/GC2-Vidi-Kerteminde#11]
Her i morges lagde jeg mærke til at alle indlejrede kort til Grundsalg fejler - der kommer kun blankt frame frem. Jeg har forsøgt både med default <script src="https://vidi.swarm.gc2.io/js/embed.js"></script> og <script src="https://vidi.kerteminde.dk/js/embed.js"></script> men det hjælper ikke.

**Comment by RomanHVarinsky** [comment]
Nu kan jeg se at nogle kort virker!? 
Denne kører fint https://kerteminde.dk/borger/miljoe-og-natur/natur/vandloeb
Kode:
![image](https://user-images.githubusercontent.com/75674760/193221321-037cd145-4296-4a10-8d36-c7d7a741978d.png)
 


Mens denne fejler https://kerteminde.dk/borger/bolig-og-byggeri/byggegrunde/flintager-munkebo
Kode:
![image](https://user-images.githubusercontent.com/75674760/193221474-be3ce994-84a3-4362-b9ef-80b06f00a013.png)


Har du en ide hvorfor?

**Comment by RomanHVarinsky** [comment]
Jeg ved ikke helt hvad der var galt, men jeg har oprettet nye projekter for hvert område, erstattet de gamle og nu virker det igen.

**Comment by mapcentia** [comment]
Jeg nåede at se det i går og det var fordi tokens var lavet på http://vidi.... (ikke https://vidi...) så dette er blevet lagt i token. Men browseren blokkerer request til http fra sider med https

**Comment by RomanHVarinsky** [comment]
Tak for uddybning. Det giver god mening - de er nu i hvert fald oprettet på ny og virker.
