### ISSUE TITLE
Konfliktsøgning på flere objekter samtidig?

### ISSUE THREAD

**Issue by RomanHVarinsky** [RomanHVarinsky/GC2-Vidi-Kerteminde#12]
Jeg er blevet spurgt om man kan lave en konfliktsøgning baseret på flere objekter. Det kunne f.eks. være matrikler, hvor der søges på matriklernes udbredelse uden at man selv skal tegne geometrien, man blot vælge nogle stykker ud ved en simpel SELECT.
Vi har pt løst det med tegneværktøjet og knappen 'Konflikt med valgte'. Men ønskescenariet ville være at udvalget fra Info bruges i konfliktsøgningen. Eller er dette afhængig af Brugergruppens ønske [001] Vidi: Moduler skal kunne undlade at trigge deaktiveringsevents?

**Comment by mapcentia** [comment]
Søgemodulet kan sende afgrænsninger ind i Tegningsmodulet, ved at sætte search.advanced=true Se denne config:
https://vidi.kerteminde.dk/app/kerteminde/?config=/api/v2/configuration/kerteminde/configuration_test_604f2adca4f10355155861.json
Efter du har søgt på en matrikel, vil den kunne findes i Tegning, hvor den så kan bruges i Konflikt.

En anden måde er at tænde matrikelkort og aktivere Konflikt. Hvis man så klikker på en matrikel, vil man efterfølgende kunne foretage en konfliktsøgning med den.

**Comment by RomanHVarinsky** [comment]
Det er en løsning på søgning på én matrikel. Men du kan ikke vælge flere matrikler på denne måde og udføre en konfliktsøgning, eller?

**Comment by mapcentia** [comment]
Gennem Søg kan du lave flere søgninger og i Tegning kan du så Søg Med Alle

**Comment by RomanHVarinsky** [comment]
OK, tak. Det er måske lidt bøvlet men det virker.
