### ISSUE TITLE
Lag tematiseret vha QGIS-projekt fil

### ISSUE THREAD

**Issue by RomanHVarinsky** [RomanHVarinsky/GC2-Vidi-Kerteminde#14]
Jeg har nogle lag til Parker og grønne områder (punkter, linjer og flader), som er tematiseret vha et QGIS-projekt. De udstilles som materialized views, for de tager nogle af PostGIS' spatiale funktioner i brug. Jeg lagde mærke til at nogle områder i tabellen er blevet slettet, da kommunen frasolgte en matrikel, men I Vidi optrådte de alligevel efter opdatering af mat.viewet. Jeg slettede cashe og tiles uden hjælp. 
Det er først lykkedes at se ændringerne efter jeg genimporterede QGIS-projektfil. Kan det passe at det skal gøres eller var der måske noget der hang?

**Comment by mapcentia** [comment]
Jeg kan ikke lige se, hvilken forskel genupload af QGIS filen skulle bevirke. QGIS Server læser det materialiseret view ved hver udtegning. Hvllken service bliver der anvendt? Den med /ows/ eller /mapcache/ i URL'en? Som udgangspunkt skal man anvende /ows/, som er "live" til det meste.

**Comment by RomanHVarinsky** [comment]
Jeg kunne nemlig heller ikke se meningen med genupload. Der bruges ikke en service, det er en direkte forbindelse til databasen gennem standard Vidi. Det kunne være der blot var noget der hang et sted - jeg holder øje med det og rapporterer hvis det sker igen
