### ISSUE TITLE
Tematisering via QGIS-projekt fejler

### ISSUE THREAD

**Issue by RomanHVarinsky** [RomanHVarinsky/GC2-Vidi-Kerteminde#16]
Efter opdatering af materialized views park_vej_havne.park_gr_omr_fl_mv/park_gr_omr_fl_dist_mv er lagene i Vidi blanke. Lagene har været tematiseret vha et QGIS-projekt, hvor også punkt- og linjelag har ligget. Disse vises fint. 
Når jeg fjerner tematiseringen og opretter en single class, kan lagene ses igen. Hænger der noget på serveren?

Jeg har også overvejet at tematisere lagene direkte i Vidi, men jeg kunne ikke knække måden at gøre det på. I QGIS bruger jeg denne funktion: `left( "vedhold_fl_label" ,2)`. Hvordan skriver man den i Vidi?

**Comment by mapcentia** [comment]
Jeg kan ikke umiddelbart se, hvad der er galt med QGIS filen. En opdatering af et mat view, skulle jo ikke ændre noget. Kan du ikke sende mig QGIS filen, som er brugt?

LEFT findes ikke i MapServer og det ser heller ikke ud til, at den har en substring funktion, hvilket er lidt overraskende. Men du kan skabe en ny kolonne i dit VIEW ved at bruge LEFT i databasen: SELECT *,LEFT( "vedhold_fl_label" ,2) AS label FROM .....

**Comment by RomanHVarinsky** [comment]
Det var en fejl på vores side, et distrikt var oprettet to gange og så går det hele i hårdknude. Nu er det rettet og distrikterne vises igen. Pudsigt dog at QGIS godt kunne vise dem, selvom flere elementer havde identiske gid'ere. Måske kan den nyere version af QGIS klare det.
