### ISSUE TITLE
Konfliktsøgning med rapport 'Lang, kun hits' hænger

### ISSUE THREAD

**Issue by RomanHVarinsky** [RomanHVarinsky/GC2-Vidi-Kerteminde#2]
Når konfliktsøgning er færdig, har man mulighed for at printe en rapport. Som default står den på 'Kompakt' og kan fint udføres. Ændrer man den til 'Lang, kun hits', bliver den ved med at hænge på 0/x, uden at komme videre. Det ser ud til at der er noget der hænger.

**Comment by mapcentia** [comment]
Jeg tester...

**Comment by mapcentia** [comment]
Det var en bug. Den er rettet og jeg implementerede samtidig parallel afvikling af print, så det går noget hurtigere

**Comment by RomanHVarinsky** [comment]
Fantastisk, tusind tak
