### ISSUE TITLE
Integration til EjdExplorer

### ISSUE THREAD

**Issue by RomanHVarinsky** [RomanHVarinsky/GC2-Vidi-Kerteminde#3]
Installationen opgraderes med integration til EjdExplorer

**Comment by mapcentia** [comment]
@RomanHVarinsky Det er lavet. Her er en test-config:
https://vidi.kerteminde.dk/app/kerteminde/?config=/api/v2/configuration/kerteminde/configuration_test_604f2adca4f10355155861.json

**Comment by RomanHVarinsky** [comment]
Den finder adresserne, men åbner kun en blank side i browseren og ikke EjdExplorer. Her i kommunen har vi lokale installationer på hver sin bærbare - kunne det have noget med det at gøre?

**Comment by mapcentia** [comment]
Det er måden EjdExplorer virker på. Det er en lokal applikation. Men man skal have defineret en custom protokol på sit netværk. Et link ser sådan ud:
ejdexpl://?mode=merge&LIFAExternalIntegrationServiceID=3365155

Som det ses bruges protokollen ejdexpl:// som skal implementeres. Når det er gjort vil browseren starte EjdExplorer. Opsætningen af protokollen skal du få LIFA til

**Comment by RomanHVarinsky** [comment]
Tak. Jeg skriver til LIFA.

**Comment by RomanHVarinsky** [comment]
Registreringsfil fra LIFA er implementeret og EjdExplorer kører. 
Tak for hjælpen.

**Comment by RomanHVarinsky** [comment]
Er det egentlig kun muligt med adresseudtræk? Kunne det forholdsvis nemt udvides med matrikeludtræk?
