### ISSUE TITLE
Planlagt teknisk anlæg

### ISSUE THREAD

**Issue by RomanHVarinsky** [RomanHVarinsky/GC2-Vidi-Kerteminde#7]
Erhvervsstyrelsen har anbefalet os at hente de vedtagne kommuneplantemaer fra Plandata. Derfor henter jeg de relevante lag fra plandatadk-skemaet i kerteminde-databasen. Jeg mangler temaet pdk_planlagttekniskanlaeg_vedtaget_v, som af en eller grund kun kan hentes som MultiLineString i stedet for MultiPolygon, som indberettet (https://geofyn.mapcentia.com/logs/858_scheduler.log). 
Temaerne pdk_planlagttekniskanlaeg_forslag/aflyst_v hentes også som MultiLineString.

**Comment by mapcentia** [comment]
@RomanHVarinsky @geofyn 
Det omtalte lag er blandet geometri (type="gml:GeometryPropertyType") så det kan ikke indlæses som MultiPolygon, da der forekommer MultiLineString. Det eneste man lige kan gøre er, at sætte Type=Auto i Scheduler, så typen bliver oprettet som GEOMETRY i tabellen. Og evt. lave views, som trækker hhv. linjer og polygoner ud, så de kan vises på kort.

**Comment by RomanHVarinsky** [comment]
@mapcentia Helt rigtigt, Martin. Tak for afklaringen.
@geofyn Jeg har oprettet høst i geofyn-databasen på tabeller 'pdk_planlagttekniskanlaeg_vedtaget/forslag/aflyst_v' med geometritype AUTO. Derefter har jeg lavet et view i plandatadk_kerteminde og fdw til kerteminde-databasen. Jeg har dog blot benyttet '_vedtaget_'-tabellen og uden at oprette supplerende views og mat.views
