### ISSUE TITLE
Implementering af nye versioner på den interne GC2

### ISSUE THREAD

**Issue by RomanHVarinsky** [RomanHVarinsky/GC2-Vidi-Kerteminde#8]
- Opdatering af GC2 til version 2022.8.1
- Opdatering af Vidi til version 2022.9.0

**Comment by mapcentia** [comment]
Done

**Comment by RomanHVarinsky** [comment]
Af en eller anden grund kan jeg kun få data-vidi-history="none" til at virke.

**Comment by mapcentia** [comment]
Jeg går ud fra, at det er på den eksterne - har lige opdateret den

**Comment by RomanHVarinsky** [comment]
Det var faktisk den interne...

**Comment by mapcentia** [comment]
Bruger du: 
https://vidi.swarm.gc2.io/js/embed.js
Den var nemlig ikke opdateret, men den er i gang med at opdatere.

Det er en god ide og bruge "egen" embed.js, så scriptet altid passer til egen Vidi. Den interne er:
https://vidi.kerteminde.dk/js/embed.js

**Comment by RomanHVarinsky** [comment]
Jeg var ikke klar over at jeg kunne/skulle skifte linket sådan - det sørger jeg for at gøre alle relevante steder. Ville det sige at når du opdaterer til nyere versioner, er det bl.a. embed.js på vidi.kerteminde.dk?

**Comment by mapcentia** [comment]
embed.js kommer sammen med Vidi, men man bruge hvilket som helst embed script fra andre installationer. Men nogle opdateringer i Vidi kræver også en opdatering i embed.js. Jeg holder https://vidi.swarm.gc2.io/js/embed.js up-to-date, men her havde jeg ikke lige været hurtig nok

**Comment by RomanHVarinsky** [comment]
Beklager :). Men det er godt at vide at der er flere muligheder.
