### ISSUE TITLE
HTTPS-certifikat på *.kerteminde.dk

### ISSUE THREAD

**Issue by RomanHVarinsky** [RomanHVarinsky/GC2-Vidi-Kerteminde#9]
Implementering af et nyt HTTPS-certifikat, gyldig frem til d.11.10.2023. Certifikatet og passwordet er sendt i to separate mails d.19.9.2022. Det nuværende certifikat udløber d.16.10.2022.

**Comment by mapcentia** [comment]
Er installeret
